"""add push_token device_id platform to users

Revision ID: 5a7396baf645
Revises: 20a9184b5051
Create Date: 2026-06-17 14:17:54.958279
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5a7396baf645'
down_revision: Union[str, None] = '20a9184b5051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uk_invitee', 'invite_records', ['invitee_user_id'])
    op.add_column('users', sa.Column('push_token', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('device_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('platform', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform')
    op.drop_column('users', 'device_id')
    op.drop_column('users', 'push_token')
    op.drop_constraint('uk_invitee', 'invite_records', type_='unique')
    # ### end Alembic commands ###
